baseURL = "https://yoursite.com"
languageCode = "en-us"
title = "QuickRef - Developer Reference"
theme = "quickref"

[params]
  description = "Share quick reference and cheat sheets for developers"
  author = "QuickRef Team"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/yourusername/quickref"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github-dark"
    lineNos = true
    tabWidth = 2

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]